name: muslimjin
description: A new Flutter project.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.3.0
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  path_provider: ^2.0.2
  sqflite: ^2.0.0+3
  intl: ^0.17.0
  logger: ^2.5.0
  geolocator: ^13.0.2
  flutter_compass: ^0.8.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - assets/
